/**
 * DLL → user-facing message mappings.
 * Source: Errors, Warnings and Validation Messages (1).xlsx
 *
 * Each row documents:
 *   - dllMessage: what the native DLL writes (results.err / logs)
 *   - userMessage: what we show in Run & Results banners and dialogs
 *
 * Lists are split by kind — errors, warnings, validations, and success are separate arrays.
 * Regenerate JSON with: python scripts/merge_portal_messages.py
 */

export type DllMessageKind = 'error' | 'warning' | 'success' | 'validation';

export interface DllMessageMapping {
  /** UI label e.g. E4, W1 (from the Excel user-friendly column). */
  id: string;
  /** Native DLL source file. */
  sourceFile: string;
  /** Raw DLL message text used for matching. */
  dllMessage: string;
  /** Message shown to the user. */
  userMessage: string;
  /** Optional DLL code #(N) for exact matching. */
  errorCode?: string;
}

export const DLL_ERROR_MESSAGES: DllMessageMapping[] = [
  {
    id: "E1",
    sourceFile: "Brent.cpp",
    dllMessage: "quiting brentgd   too many times around ...",
    userMessage: "(E1) Review the input values for unrealistic routing, timing, or capacity settings.",
  },
  {
    id: "E2",
    sourceFile: "calc.cpp",
    dllMessage: "Cannot Calculate anything.\n No Parts have been added yet.",
    userMessage: "(E2) Missing Products",
  },
  {
    id: "E3",
    sourceFile: "calc.cpp",
    dllMessage: "error before ...set demand start",
    userMessage: "(E3) Check demand/production quantity inputs.",
  },
  {
    id: "E4",
    sourceFile: "calc1.cpp",
    dllMessage: "ERROR: #(41) \n Mean Time To Failure \n for equipment \n is too small. Please change value",
    userMessage: "(E4) Mean time to Failure: Enter a realistic positive failure-time value.",
    errorCode: "41",
  },
  {
    id: "E5",
    sourceFile: "calc1.cpp",
    dllMessage: "ERROR: #(7)\n Number of types of equipment is %d and exceeds limit of %d \n Some internal routing equations cannot be solved due to lack of memory",
    userMessage: "(E5) No of Equipment types exceeds system limit.",
    errorCode: "7",
  },
  {
    id: "E6",
    sourceFile: "calc1.cpp",
    dllMessage: "MAJOR ERROR: #(103) CONTACT BUILD TO DEMAND.COM \n Equipment wait time < 0.0",
    userMessage: "(E6) Invalid equipment wait time. Review equipment capacity, operation times, and routing inputs.",
    errorCode: "103",
  },
  {
    id: "E7",
    sourceFile: "calc1.cpp",
    dllMessage: "MAJOR ERROR: #(103) CONTACT CONTACT BUILD TO DEMAND.COM \n Equipment wait time < 0.0",
    userMessage: "(E7) Invalid negative equipment wait time. Review equipment capacity, operation times, and routing inputs.",
    errorCode: "103",
  },
  {
    id: "E8",
    sourceFile: "calc1.cpp",
    dllMessage: "INTERNAL ERROR: #(84)\n Operation is a sink for pieces.\n There are no `FROM-TO' routings from this operation?",
    userMessage: "(E8) Operation/Routing error. Check FROM-TO routing path.",
    errorCode: "84",
  },
  {
    id: "E9",
    sourceFile: "calc1.cpp",
    dllMessage: "INTERNAL ERROR: #(85)\n Operation data cannot be found.\n There is no `OPERATION ASSIGNMENT' record for this operation",
    userMessage: "(E9) Operation/Routing error. Missing operation assignment.",
    errorCode: "85",
  },
  {
    id: "E10",
    sourceFile: "calc11.cpp",
    dllMessage: "in fvalue Internal error, calculation stopped",
    userMessage: "(E10) Input data error. Review the all inputs and try again.",
  },
  {
    id: "E11",
    sourceFile: "calc11.cpp",
    dllMessage: "quiting frprmn",
    userMessage: "(E11) Unrealistic routing or capacity settings.",
  },
  {
    id: "E12",
    sourceFile: "calc2.cpp",
    dllMessage: "INTERNAL ERROR: #(XX)\n Number in Labor group is too small.\n Value is %f ??",
    userMessage: "(E12) Invalid Labor group quantiy",
  },
  {
    id: "E13",
    sourceFile: "calc2.cpp",
    dllMessage: "INTERNAL ERROR: #(XX)\n Number in Labor group %s is too small.\n Value is %f ??",
    userMessage: "(E13) Invalid Labor group quantiy",
  },
  {
    id: "E14",
    sourceFile: "calc3.cpp",
    dllMessage: "ERROR CACALC aoper null",
    userMessage: "(E14) Missing Operation or Routing details",
  },
  {
    id: "E15",
    sourceFile: "calc3.cpp",
    dllMessage: "MAJOR ERROR: #(47b) \n CONTACT BUILD TO DEMAND.COM \n Inversion of arrival variances Equipment",
    userMessage: "(E15) Equipment variability Issue. Review equipment MTTF/MTTR, routing, and variability inputs.",
    errorCode: "47b",
  },
  {
    id: "E16",
    sourceFile: "calc3.cpp",
    dllMessage: "INTERNAL ERROR: #(48) \n Numerical Problems \n Equipment Varability Routing cannot be solved",
    userMessage: "(E16) Equipment variability Issue. Review equipment MTTF/MTTR, routing, and variability inputs.",
    errorCode: "48",
  },
  {
    id: "E17",
    sourceFile: "calc5.cpp",
    dllMessage: "error in doall visits",
    userMessage: "(E17) Routing incomplete",
  },
  {
    id: "E18",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(6)\n Number of operations for product exceeds limit of %d \n The routing equations cannot be solved due to lack of memory",
    userMessage: "(E18) Operation count not supported. Reduce no of operations.",
    errorCode: "6",
  },
  {
    id: "E19",
    sourceFile: "calc5.cpp",
    dllMessage: "mem error  !!!",
    userMessage: "(E19) Unexpected memory error. Contact support@trooba.com",
  },
  {
    id: "E20",
    sourceFile: "calc5.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(12) \n Insufficient Memory Space. Cannot Solve Routing equations",
    userMessage: "(E20) Unexpected memory error. Contact support@trooba.com",
    errorCode: "12",
  },
  {
    id: "E21",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(69) \n Routing cannot be solved for Product. \n CHECK IF THERE IS A PATH FROM EVERY OPERATION TO 'STOCK'.",
    userMessage: "(E21) Routing incomplete",
    errorCode: "69",
  },
  {
    id: "E22",
    sourceFile: "calc5.cpp",
    dllMessage: "Error: \n No pieces of Part %s are being routed to STOCK !\n Please change routing...",
    userMessage: "(E22) Routing/Operations Error. Nothing routed to STOCK.",
  },
  {
    id: "E23",
    sourceFile: "calc5.cpp",
    dllMessage: "Error: \n No pieces of product are being routed to STOCK !\n Please change routing...(1)",
    userMessage: "(E23) Routing/Operations Error. Nothing routed to STOCK.",
  },
  {
    id: "E24",
    sourceFile: "calc5.cpp",
    dllMessage: "INTERNAL ERROR: #(21b) \n Routing cannot be solved for product",
    userMessage: "(E24) Routing/Operations Error. Nothing routed to STOCK.",
    errorCode: "21b",
  },
  {
    id: "E25",
    sourceFile: "calc5.cpp",
    dllMessage: "Error: \n No pieces of Part %s are being routed to STOCK !\n Please change routing...",
    userMessage: "(E25) Routing/Operations Error. Nothing routed to STOCK.",
  },
  {
    id: "E26",
    sourceFile: "calc5.cpp",
    dllMessage: "Error: \n No pieces of product are being routed to STOCK !\n Please change routing...(2)",
    userMessage: "(E26) Routing/Operations Error. Nothing routed to STOCK.",
  },
  {
    id: "E27",
    sourceFile: "calc5.cpp",
    dllMessage: "INTERNAL ERROR: #(21c) \n Routing cannot be solved for product",
    userMessage: "(E27) Routing/Operations Error.",
    errorCode: "21c",
  },
  {
    id: "E28",
    sourceFile: "calc5.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(22a) \n Insufficient Memory to calculate No. times operations done for product",
    userMessage: "(E28) Memory Error. Contact support@trooba.com",
    errorCode: "22a",
  },
  {
    id: "E29",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(74) \n For part %s %% of pieces Routed out of DOCK does not equal  100.0%%",
    userMessage: "(E29) Routing/Operations Error. Routing percentages out of DOCK must total 100%.",
    errorCode: "74",
  },
  {
    id: "E30",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(74) \n %% of pieces Routed out of DOCK does not equal 100.0%%",
    userMessage: "(E30) Routing/Operations Error. Routing percentages out of DOCK must total 100%.",
    errorCode: "74",
  },
  {
    id: "E31",
    sourceFile: "calc5.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(22c) \n Insufficient Memory to calculate \n No. times operations done for product",
    userMessage: "(E31) Memory Error. Contact support@trooba.com",
    errorCode: "22c",
  },
  {
    id: "E32",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(75) \n For part %s Total Proportion \n Assigned to Operation %s is not equal to 100.0%%",
    userMessage: "(E32) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "75",
  },
  {
    id: "E33",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(75) \n Total Proportion \n Assigned to Operation is not equal to 100.0%%",
    userMessage: "(E33) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "75",
  },
  {
    id: "E34",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(76c) \n %% of pieces routed \n out of operation does not equal  100.0%%",
    userMessage: "(E34) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "76c",
  },
  {
    id: "E35",
    sourceFile: "calc5.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(22d) \n Insufficient Memory to calculate \n No. times operations done for product",
    userMessage: "(E35) Memory Error. Contact support@trooba.com",
    errorCode: "22d",
  },
  {
    id: "E36",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(75b) \n For part %s Total Proportion \n Assigned to Operation %s is not equal to 100.0%%",
    userMessage: "(E36) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "75b",
  },
  {
    id: "E37",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(75b) \n Total Proportion \n Assigned to operation is not equal to 100.0%%",
    userMessage: "(E37) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "75b",
  },
  {
    id: "E38",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(76b) \n For part %s %% of pieces \n routed out of Operation %s does not equal 100.0%%",
    userMessage: "(E38) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "76b",
  },
  {
    id: "E39",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(76b) \n %% of pieces \n routed out of operation does not equal 100.0%%",
    userMessage: "(E39) Routing/Operations Error. Routing percentages must total 100%.",
    errorCode: "76b",
  },
  {
    id: "E40",
    sourceFile: "calc5.cpp",
    dllMessage: "MAJOR ERROR: #(26) \n CONTACT BUILD TO DEMAND.COM \n CANNOT FIND 'TO' OPERATION listed as a 'FROM' OPERATION",
    userMessage: "(E40) Routing/Operations Error.",
    errorCode: "26",
  },
  {
    id: "E41",
    sourceFile: "calc5.cpp",
    dllMessage: "ERROR: #(77) \n All pieces go to SCRAP from an operation.  This is not allowed.  (Hint: send 0.0001%% to STOCK)",
    userMessage: "(E41) Routing/Operations Error. All pieces are routed to SCRAP.",
    errorCode: "77",
  },
  {
    id: "E42",
    sourceFile: "calc7.cpp",
    dllMessage: "MAJOR ERROR: #201 \n No operations for a product.",
    userMessage: "(E42) Product missing operations/routing.",
    errorCode: "201",
  },
  {
    id: "E43",
    sourceFile: "calc7.cpp",
    dllMessage: "at check_eq start error no routes ?  %s %i %i",
    userMessage: "(E43) Product missing operations/routing.",
  },
  {
    id: "E44",
    sourceFile: "calc7.cpp",
    dllMessage: "ERROR: #(42) \n No Equipment assigned for \n Part and Operation",
    userMessage: "(E44) Equipment assignment missing.",
    errorCode: "42",
  },
  {
    id: "E45",
    sourceFile: "calc9.cpp",
    dllMessage: "can't write to lot.res",
    userMessage: "(E45) The system could not save the results. Contact support@trooba.com",
  },
  {
    id: "E46",
    sourceFile: "calc9_1.cpp",
    dllMessage: "Internal error, calculation stopped",
    userMessage: "(E46) Internal data error. Contact support@trooba.com",
  },
  {
    id: "E47",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(6) \n Equipment uses an unknown Labor Group",
    userMessage: "(E47) Equipment assigned to incorrect labor group.",
    errorCode: "6",
  },
  {
    id: "E48",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(7) \n Operation is tied to an unknown Product",
    userMessage: "(E48) An operation/routing linked to invalid product.",
    errorCode: "7",
  },
  {
    id: "E49",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(8) \n Operation is tied to an unknown Equipment group",
    userMessage: "(E49) Operation linked to incorrect equipment group.",
    errorCode: "8",
  },
  {
    id: "E50",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(9) \n Routing is tied to an unknown Product",
    userMessage: "(E50) An operation/routing linked to invalid product.",
    errorCode: "9",
  },
  {
    id: "E51",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(10) \n Routing FROM is tied to an unknown Operation",
    userMessage: "(E51) Routing/Operations Error. A routing FROM operation does not exist.",
    errorCode: "10",
  },
  {
    id: "E52",
    sourceFile: "dll2.cpp",
    dllMessage: "INTERNAL ERROR: #(11) \n Routing TO is tied to an unknown Operation",
    userMessage: "(E52) Routing/Operations Error. A routing TO operation does not exist.",
    errorCode: "11",
  },
  {
    id: "E53",
    sourceFile: "dll2.cpp",
    dllMessage: "internal error/data error ... NO write_results in run it",
    userMessage: "(E53) Internal error. Contact support@trooba.com",
  },
  {
    id: "E54",
    sourceFile: "io_code.cpp",
    dllMessage: "IN GROUP  GROUP                FAILURE  REPAIR   RATE (%%)  MULTIPLIER  MULTIPLIER  MULTIPLIER",
    userMessage: "(E54) Equipment MTTF/MTTR error.",
  },
  {
    id: "E55",
    sourceFile: "log.h",
    dllMessage: "ERROR",
    userMessage: "(E55) Check Input data.",
  },
  {
    id: "E56",
    sourceFile: "log.h",
    dllMessage: "ERROR",
    userMessage: "(E56) Internal error. Contact support@trooba.com",
  },
  {
    id: "E57",
    sourceFile: "log.h",
    dllMessage: "Unknown logging level '",
    userMessage: "(E57) Internal error. Contact support@trooba.com",
  },
  {
    id: "E58",
    sourceFile: "log.h",
    dllMessage: "Error in NowTime()",
    userMessage: "(E58) Internal error. Contact support@trooba.com",
  },
  {
    id: "E59",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot find Product for an operation",
    userMessage: "(E59) An operation/routing linked to invalid product.",
  },
  {
    id: "E60",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot find equipment for an operation",
    userMessage: "(E60) Operation linked to incorrect equipment group.",
  },
  {
    id: "E61",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot find DOCK for a product ??",
    userMessage: "(E61) Routing/Operations Error. Missing DOCK operation.",
  },
  {
    id: "E62",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot find STOCK for a product ??",
    userMessage: "(E62) Routing/Operations Error. Missing STOCK operation.",
  },
  {
    id: "E63",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot find STOCK for a product ??",
    userMessage: "(E63) Routing/Operations Error. Missing STOCK operation.",
  },
  {
    id: "E64",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot add operation",
    userMessage: "(E64) Routing/Operations Error.",
  },
  {
    id: "E65",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E65) Internal error. Contact support@trooba.com",
  },
  {
    id: "E66",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E66) Internal error. Contact support@trooba.com",
  },
  {
    id: "E67",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E67) Internal error. Contact support@trooba.com",
  },
  {
    id: "E68",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E68) Internal error. Contact support@trooba.com",
  },
  {
    id: "E69",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E69) Internal error. Contact support@trooba.com",
  },
  {
    id: "E70",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E70) Internal error. Contact support@trooba.com",
  },
  {
    id: "E71",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for results data",
    userMessage: "(E71) Internal error. Contact support@trooba.com",
  },
  {
    id: "E72",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot open error file to write message !1!?\n %s",
    userMessage: "(E72) Internal error. Contact support@trooba.com",
  },
  {
    id: "E73",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot open error file to write message !2!??\n %s",
    userMessage: "(E73) Internal error. Contact support@trooba.com",
  },
  {
    id: "E74",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Cannot open error file to write message %s !3!??\n %s",
    userMessage: "(E74) Internal error. Contact support@trooba.com",
  },
  {
    id: "E75",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Can open error file to write message %s !3!??\n %s %f",
    userMessage: "(E75) Internal error. Contact support@trooba.com",
  },
  {
    id: "E76",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for download data",
    userMessage: "(E76) Internal error. Contact support@trooba.com",
  },
  {
    id: "E77",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for reformatted MRP data",
    userMessage: "(E77) Internal MRP data error. Contact support@trooba.com",
  },
  {
    id: "E78",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Read error Infile 4 ?? \n stopping at line  ...",
    userMessage: "(E78) Internal error. Contact support@trooba.com",
  },
  {
    id: "E79",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for download data",
    userMessage: "(E79) Internal error. Contact support@trooba.com",
  },
  {
    id: "E80",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for reformatted MRP data",
    userMessage: "(E80) Internal MRP data error. Contact support@trooba.com",
  },
  {
    id: "E81",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Read error Infile1 ?? \n stopping at line  ...",
    userMessage: "(E81) Internal error. Contact support@trooba.com",
  },
  {
    id: "E82",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for download data",
    userMessage: "(E82) Internal error. Contact support@trooba.com",
  },
  {
    id: "E83",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for reformatted MRP data",
    userMessage: "(E83) Internal MRP data error. Contact support@trooba.com",
  },
  {
    id: "E84",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Read error Infile 2 ?? \n stopping at line  ...",
    userMessage: "(E84) Internal error. Contact support@trooba.com",
  },
  {
    id: "E85",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for download data",
    userMessage: "(E85) Internal error. Contact support@trooba.com",
  },
  {
    id: "E86",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "ERROR : \n Cannot open file %s for reformatted MRP data",
    userMessage: "(E86) Internal MRP data error. Contact support@trooba.com",
  },
  {
    id: "E87",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "Read error Infile 3 ?? \n stopping at line  ...",
    userMessage: "(E87) Internal error. Contact support@trooba.com",
  },
  {
    id: "E88",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(18a) \n Insufficient Memory to add ANY LABOR GROUP",
    userMessage: "(E88) Memory Error. Contact support@trooba.com",
    errorCode: "18a",
  },
  {
    id: "E89",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(18b) \n Insufficient Memory to add ANY EQUIPMENT GROUP",
    userMessage: "(E89) Memory Error. Contact support@trooba.com",
    errorCode: "18b",
  },
  {
    id: "E90",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(18c) \n Insufficient Memory to add ANY PART DATA",
    userMessage: "(E90) Memory Error. Contact support@trooba.com",
    errorCode: "18c",
  },
  {
    id: "E91",
    sourceFile: "mpx_c1.cpp",
    dllMessage: "INSUFFICIENT MEMORY: #(18d) \n Insufficient Memory to add ANY WHAT-IF CASES",
    userMessage: "(E91) Memory Error. Contact support@trooba.com",
    errorCode: "18d",
  },
  {
    id: "E92",
    sourceFile: "nrutil.c",
    dllMessage: "Numerical Recipes run-time error...",
    userMessage: "(E92) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E93",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in vector()",
    userMessage: "(E93) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E94",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in ivector()",
    userMessage: "(E94) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E95",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in cvector()",
    userMessage: "(E95) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E96",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in lvector()",
    userMessage: "(E96) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E97",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in dvector()",
    userMessage: "(E97) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E98",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 1 in matrix()",
    userMessage: "(E98) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E99",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 2 in matrix()",
    userMessage: "(E99) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E100",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 1 in matrix()",
    userMessage: "(E100) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E101",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 2 in matrix()",
    userMessage: "(E101) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E102",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 1 in matrix()",
    userMessage: "(E102) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E103",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 2 in matrix()",
    userMessage: "(E103) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E104",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in submatrix()",
    userMessage: "(E104) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E105",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in convert_matrix()",
    userMessage: "(E105) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E106",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure in convert_matrix()",
    userMessage: "(E106) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E107",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 1 in f3tensor()",
    userMessage: "(E107) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E108",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 2 in f3tensor()",
    userMessage: "(E108) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E109",
    sourceFile: "nrutil.c",
    dllMessage: "allocation failure 3 in f3tensor()",
    userMessage: "(E109) Memory Error. Contact support@trooba.com",
  },
  {
    id: "E110",
    sourceFile: "portal/dll_full_calculate.py",
    dllMessage: "Equipment: {resourceName} ({totalUtil}%)",
    userMessage: "(E110) Equipment is over the utilization limit.",
  },
  {
    id: "E111",
    sourceFile: "portal/dll_full_calculate.py",
    dllMessage: "Labor: {resourceName} ({totalUtil}%)",
    userMessage: "(E111) Labor is over the utilization limit.",
  },
];

export const DLL_WARNING_MESSAGES: DllMessageMapping[] = [
  {
    id: "W1",
    sourceFile: "calc.cpp",
    dllMessage: "Warning: Production Level is NOT SUSTAINABLE. \nLabor resources will be overutilized. \nManufacturing Cycle Time and WIP cannot be calculated.",
    userMessage: "(W1) Production not sustainable. Labor is overcapacity. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W2",
    sourceFile: "calc.cpp",
    dllMessage: "Warning: Production Level is NOT SUSTAINABLE. \nEquipment resources will be overutilized. \nManufacturing Cycle Time and WIP cannot be calculated.",
    userMessage: "(W2) Production not sustainable. Equipment capacity overloaded. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W3",
    sourceFile: "calc1.cpp",
    dllMessage: "LABOR and EQUIPMENT resources are over-utilized.",
    userMessage: "(W3) Production not sustainable. Labor and equipment are over capacity. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W4",
    sourceFile: "calc1.cpp",
    dllMessage: "EQUIPMENT resources are over-utilized.",
    userMessage: "(W4) Production not sustainable. Equipment capacity overloaded. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W5",
    sourceFile: "calc1.cpp",
    dllMessage: "LABOR resources are over-utilized.",
    userMessage: "(W5) Production not sustainable. Labor is overcapacity. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W6",
    sourceFile: "calc1.cpp",
    dllMessage: "WARNING:\n \nProduction level is not sustainable.\n %s \n Manufacturing Cycle Time and WIP cannot be calculated.",
    userMessage: "(W6) Production not sustainable. Labor and equipment are over capacity. Adjust capacity, reduce demand, or rebalance routing.",
  },
  {
    id: "W7",
    sourceFile: "calc1.cpp",
    dllMessage: "INTERNAL ERROR: #(71)\n Contact Build to Demand at  BUILD TO DEMAND.COM \n Flow time details are questionable - \n Calculation will continue",
    userMessage: "(W7) Flow-time results unreliable. The calculation continued, but you should review routing, capacity, and timing inputs.",
    errorCode: "71",
  },
  {
    id: "W8",
    sourceFile: "calc2.cpp",
    dllMessage: "WARNING: #(89) \n Labor Group %s is not Used",
    userMessage: "(W8) Unassigned Labor group. Remove or assign to operation",
    errorCode: "89",
  },
  {
    id: "W9",
    sourceFile: "calc2.cpp",
    dllMessage: "WARNING: #(89) \n Labor Group is not Used",
    userMessage: "(W9) Unassigned Labor group. Remove or assign to operation",
    errorCode: "89",
  },
  {
    id: "W10",
    sourceFile: "calc3.cpp",
    dllMessage: "MAJOR ERROR: #(47a) \n CONTACT BUILD TO DEMAND.COM \n warning at line 113",
    userMessage: "(W10) Unreliable results. Contact support@trooba.com",
    errorCode: "47a",
  },
  {
    id: "W11",
    sourceFile: "calc5.cpp",
    dllMessage: "WARNING: #(56) \n   Transfer Batch Size is greater than lotsize.\n Transfer Batch Size should be -1 (meaning it is the same as the lotsize) or less than or equal to Lotsize.",
    userMessage: "(W11) Transfer batch size cannot be greater than lot size.",
    errorCode: "56",
  },
  {
    id: "W12",
    sourceFile: "calc7.cpp",
    dllMessage: "WARNING: #(80)\n  Equipment Time=0.0 and Labor Time>0.0 for an operation  \n Please check operation time data",
    userMessage: "(W12) An operation has labor time but zero equipment time.",
    errorCode: "80",
  },
  {
    id: "W13",
    sourceFile: "calc7.cpp",
    dllMessage: "WARNING: #(83)\n Equipment Time  setup %f run %f is less than Labor Time setup %f run %f for an operation. Be sure you want more than 1 person assigned to the operation.",
    userMessage: "(W13) Equipment time is lower than labor time for an operation. Confirm multiple people are intentionally assigned to that operation.",
    errorCode: "83",
  },
  {
    id: "W14",
    sourceFile: "calc7.cpp",
    dllMessage: "WARNING: #(70) \n The ratio of labor to equipment exceeds the available laborers",
    userMessage: "(W14) Assigned labor-to-equipment ratio is higher than available labor capacity. Reduce assigned labor or add labor capacity.",
    errorCode: "70",
  },
  {
    id: "W15",
    sourceFile: "io_code.cpp",
    dllMessage: "At prob warn err results.err",
    userMessage: "(W15) Internal error. Contact support@trooba.com",
  },
  {
    id: "W16",
    sourceFile: "io_code.cpp",
    dllMessage: "warning/error!!! %d   %s   %s %s %s   %s %s %s",
    userMessage: "(W16) Internal error. Contact support@trooba.com",
  },
  {
    id: "W17",
    sourceFile: "log.h",
    dllMessage: "WARNING",
    userMessage: "(W17) Review input data. Input data adjustments needed for reliable output.",
  },
  {
    id: "W18",
    sourceFile: "log.h",
    dllMessage: "WARNING",
    userMessage: "(W18) Review input data. Input data adjustments needed for reliable output.",
  },
  {
    id: "W19",
    sourceFile: "portal/dll_full_calculate.py",
    dllMessage: 'Equipment "{resourceName}" util ({totalUtil}%) > limit ({utilLimit}%)',
    userMessage: "(W19) Equipment utilization exceeds the configured limit.",
  },
  {
    id: "W20",
    sourceFile: "portal/dll_full_calculate.py",
    dllMessage: 'Labor "{resourceName}" util ({totalUtil}%) > limit ({utilLimit}%)',
    userMessage: "(W20) Labor utilization exceeds the configured limit.",
  },
];

export const VALIDATION_MESSAGES: DllMessageMapping[] = [
  { id: "V1", sourceFile: "portal/calculationEngine.ts", dllMessage: "No products defined.", userMessage: "(V1) No products defined." },
  { id: "V2", sourceFile: "portal/calculationEngine.ts", dllMessage: "No operations defined for any product.", userMessage: "(V2) No operations defined for any product." },
  { id: "V3", sourceFile: "portal/calculationEngine.ts", dllMessage: "MCT Conversion (operations per MCT time unit) must be greater than 0 — General Data → Time Settings.", userMessage: "(V3) MCT Conversion (operations per MCT time unit) must be greater than 0 — General Data → Time Settings." },
  { id: "V4", sourceFile: "portal/calculationEngine.ts", dllMessage: "Production Period Conversion (MCT units per production period) must be greater than 0 — General Data → Time Settings.", userMessage: "(V4) Production Period Conversion (MCT units per production period) must be greater than 0 — General Data → Time Settings." },
  { id: "V5", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Equipment "{equipmentName}" references a labor group that does not exist — assign a valid group on Equipment Data.', userMessage: "(V5) Equipment references a labor group that does not exist — assign a valid group on Equipment Data." },
  { id: "V6", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Equipment "{equipmentName}": MTTF must be ≥ 1 ({opsTimeUnit}). Use Equipment Data to set mean time to failure.', userMessage: "(V6) Equipment MTTF must be ≥ 1. Use Equipment Data to set mean time to failure." },
  { id: "V7", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Operation "{operationName}" references equipment that does not exist — fix equipment assignment on Operations Data.', userMessage: "(V7) Operation references equipment that does not exist — fix equipment assignment on Operations Data." },
  { id: "V8", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": add at least one operation (Operations Data).', userMessage: "(V8) Product needs at least one operation (Operations Data)." },
  { id: "V9", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": add at least one routing row with From and To operations (Routing Data).', userMessage: "(V9) Product needs at least one routing row with From and To operations (Routing Data)." },
  { id: "V10", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": every routing row needs both From operation and To operation filled in (Routing Data).', userMessage: "(V10) Every routing row needs both From operation and To operation filled in (Routing Data)." },
  { id: "V11", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": routing must include at least one From step and one To step (Routing Data).', userMessage: "(V11) Routing must include at least one From step and one To step (Routing Data)." },
  { id: "V12", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": Lot Size must be ≥ 1 — Product Data.', userMessage: "(V12) Product lot size must be ≥ 1 — Product Data." },
  { id: "V13", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": Demand cannot be negative — Product Data.', userMessage: "(V13) Product demand cannot be negative — Product Data." },
  { id: "V14", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Equipment "{equipmentName}": Count must be ≥ 1 for standard equipment — Equipment Data.', userMessage: "(V14) Standard equipment count must be ≥ 1 — Equipment Data." },
  { id: "V15", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Labor "{laborName}": Count must be ≥ 1 — Labor Data.', userMessage: "(V15) Labor count must be ≥ 1 — Labor Data." },
  { id: "V16", sourceFile: "portal/calculationEngine.ts", dllMessage: "No labor groups defined.", userMessage: "(V16) No labor groups defined." },
  { id: "V17", sourceFile: "portal/calculationEngine.ts", dllMessage: "No equipment groups defined.", userMessage: "(V17) No equipment groups defined." },
  { id: "V18", sourceFile: "portal/calculationEngine.ts", dllMessage: 'Product "{productName}": routing from "{fromOperation}" sums to {percentTotal}%, not 100%.', userMessage: "(V18) Routing percentages from an operation do not sum to 100%." },
];

export const DLL_SUCCESS_MESSAGES: DllMessageMapping[] = [
  {
    id: "R4",
    sourceFile: "calc.cpp",
    dllMessage: "Value Stream Modeling EVALUATION IS COMPLETED\n However the resouce utilization is very high and the Manufacturing Cycle Time numbers are not as accurate.",
    userMessage: "Evaluation completed. Resource utilization is very high, so cycle-time and WIP results may be less accurate. Review overloaded resources before using the results.",
  },
];

export const ALL_DLL_MESSAGE_MAPPINGS: readonly DllMessageMapping[] = [
  ...DLL_ERROR_MESSAGES,
  ...DLL_WARNING_MESSAGES,
  ...VALIDATION_MESSAGES,
  ...DLL_SUCCESS_MESSAGES,
] as const;

